import React from 'react';
import {ScrollView, Text, View} from 'react-native';

import Header from '../components/header';
import {Routes, ScreenProps} from '../navigation';
import useStyles from '../styles/screens/terms';

const About = (props: ScreenProps<any>) => {
  const styles = useStyles();

  const navigateTo = (screen: string) => {
    props.navigation.navigate(screen);
  };

  return (
    <View style={styles.container}>
      <Header title="Terms of Use" isPop />
      <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.listContainer}>
        <View style={styles.itemContainer}>
          <Text style={styles.subtitle}>
            Gargantua Exploration Co., having its office at 3-5-11, Hyderabad, India - 505301 (“G
            Player”, “we”, “us” or “our”), owns/ operates ‘over the top” on demand digital
            application/services under the brand name “Gargantua Exploration Co.”. {'\n\n'}
            This user agreement (“User Agreement”) shall be read in conjunction and together with
            the{' '}
            <Text style={styles.link} onPress={() => navigateTo(Routes.Privacy)}>
              Privacy Policy
            </Text>{' '}
            which forms an integral part of the User Agreement between G Player and you (“User”,
            “You” or “Your”) in relation to Your access to use of the Services. . The Service shall
            also mean and include the Subscription Service (as defined hereunder), by User. {'\n\n'}
            This User Agreement shall be considered as an “electronic records” as read and construed
            under Indian Contract Act, 1872 of India and amendment thereof or as construed under
            equivalent local law of Your jurisdiction and rules thereunder as applicable. This User
            Agreement is generated by a computer system and does not require any physical or digital
            signatures. {'\n\n'}
            User Agreement is a legal and binding agreement between the User of the Service and G
            Player and states the terms that govern Your use and access of the Service. By accessing
            this Service, You consent, agree and undertake to abide, be bound by and adhere to the
            User Agreement and if You do not agree to these User Agreement, You should not access or
            use the Service. Your access to the Services shall be construed that you agree to the
            User Agreement and Privacy Policy. We reserve the right, at our sole discretion, to
            change, modify or otherwise alter these User Agreement at any time without prior notice.
            Such changes and/or modifications shall become effective immediately upon being
            posted/published on the Service herein. Your continued use of the Service following the
            posting of changes and/or modifications shall constitute Your acceptance of any revised
            User Agreement. We retain the right at any time to deny or suspend access to all or part
            of the Services to anyone who we believe will violate or has violated any of the terms
            of the User Agreement.
          </Text>
        </View>
      </ScrollView>
    </View>
  );
};

export default About;
